# Generated by Django 5.2.4 on 2025-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField()),
                ('user_email', models.CharField()),
                ('user_mobile', models.CharField()),
                ('user_password', models.CharField()),
            ],
        ),
    ]
