# Generated by Django 5.2.4 on 2025-07-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_first_name', models.CharField()),
                ('owner_last_name', models.CharField()),
                ('owner_mobile', models.CharField()),
                ('owner_address', models.TextField()),
                ('owner_type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_first_name', models.CharField()),
                ('party_last_name', models.CharField()),
                ('party_mobile', models.CharField()),
                ('party_email', models.CharField()),
                ('party_address', models.TextField()),
                ('party_city', models.CharField()),
                ('party_gst_number', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.owner')),
            ],
        ),
    ]
