# Generated by Django 5.2.4 on 2025-07-27 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField()),
                ('to_city', models.CharField()),
                ('cost', models.IntegerField()),
                ('advance_amount', models.IntegerField()),
                ('balance_amount', models.IntegerField()),
                ('to_pay_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField()),
                ('booking_date', models.DateField()),
                ('total_hire', models.IntegerField()),
                ('advance_amount', models.IntegerField()),
                ('balance_amount', models.IntegerField()),
                ('to_pay_amount', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('cash', models.IntegerField()),
                ('local', models.IntegerField()),
                ('hamali', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('st_charges', models.IntegerField()),
                ('other_charges', models.IntegerField()),
                ('remark', models.CharField()),
                ('sub_total', models.IntegerField()),
                ('previous_amount', models.IntegerField()),
                ('pending_amount', models.IntegerField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.party')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vehicle')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.route')),
            ],
        ),
    ]
