# Generated by Django 5.2.4 on 2025-07-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(default=''),
        ),
    ]
