# Generated by Django 5.2.4 on 2025-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_bookvehicle_vehicletype_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_pending_amt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
