# Generated by Django 5.2.4 on 2025-07-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_party_party_pending_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='party_last_name',
        ),
    ]
