# Generated by Django 5.2.4 on 2025-07-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_party_party_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='party_first_name',
            new_name='party_name',
        ),
    ]
