# Generated by Django 5.2.4 on 2025-07-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_party_first_name_party_party_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='route',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
