# Generated by Django 5.2.4 on 2025-07-29 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_booking_route_delete_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_city',
            field=models.CharField(default='now'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='to_city',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
