# Generated by Django 5.2.4 on 2025-07-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_booking_from_city_booking_to_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvehicle',
            name='advance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookvehicle',
            name='balance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookvehicle',
            name='from_city',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='bookvehicle',
            name='from_date',
            field=models.DateField(blank=True, default='2001-01-02'),
        ),
        migrations.AddField(
            model_name='bookvehicle',
            name='to_city',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='bookvehicle',
            name='to_date',
            field=models.DateField(blank=True, default='2001-01-02'),
        ),
        migrations.AddField(
            model_name='bookvehicle',
            name='to_pay_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookvehicle',
            name='total_hire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookvehicle',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.vehicle'),
            preserve_default=False,
        ),
    ]
