# Generated by Django 5.2.4 on 2025-07-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_bookvehicle_advance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvehicle',
            name='from_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookvehicle',
            name='to_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
