# Generated by Django 5.2.4 on 2025-07-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_bookvehicle_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookvehicle',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='bookvehicle',
            name='to_date',
        ),
    ]
