# Generated by Django 5.2.4 on 2025-07-30 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_booking_loading_date_booking_unloading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='online',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='utr',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
