# Generated by Django 5.2.4 on 2025-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_booking_online_booking_transaction_id_booking_utr'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount_to_paid_to_vehicle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_amount_to_pay_to_vehicle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_hire_to_pay_to_vehicle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='balance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='balance_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='party_pending_amt',
            field=models.IntegerField(default=0),
        ),
    ]
