# Generated by Django 5.2.4 on 2025-07-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_booking_advance_amount_to_paid_to_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='balance_amount',
            field=models.IntegerField(default=0),
        ),
    ]
