# Generated by Django 5.2.4 on 2025-07-31 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_vehicle_balance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField()),
                ('cash', models.IntegerField(default=0)),
                ('online', models.IntegerField(default=0)),
                ('transaction_id', models.CharField()),
                ('utr', models.CharField()),
                ('total', models.IntegerField()),
                ('previous_amount', models.IntegerField()),
                ('pending_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.party')),
            ],
        ),
    ]
