# Generated by Django 5.2.4 on 2025-07-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_paymentrecived'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField()),
                ('cash', models.IntegerField(default=0)),
                ('online', models.IntegerField(default=0)),
                ('transaction_id', models.CharField()),
                ('utr', models.CharField()),
                ('total', models.IntegerField()),
                ('previous_amount', models.IntegerField()),
                ('balance_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vehicle')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vehicletype')),
            ],
        ),
    ]
