# Generated by Django 5.2.4 on 2025-08-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_paymentsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField()),
                ('owner_mobile', models.CharField()),
                ('owner_address', models.TextField()),
                ('owner_type', models.CharField()),
                ('balance_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField()),
                ('party_mobile', models.CharField()),
                ('party_email', models.CharField()),
                ('party_address', models.TextField()),
                ('party_city', models.CharField()),
                ('party_gst_number', models.CharField()),
                ('party_pending_amt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_first_name',
            new_name='owner_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='static/user/user_profile_image/'),
        ),
        migrations.CreateModel(
            name='DeletedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('loading_date', models.DateField(auto_now_add=True)),
                ('unloading_date', models.DateField(auto_now_add=True)),
                ('from_city', models.CharField()),
                ('to_city', models.CharField()),
                ('total_hire', models.IntegerField()),
                ('advance_amount', models.IntegerField()),
                ('balance_amount', models.IntegerField()),
                ('to_pay_amount', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('cash', models.IntegerField()),
                ('online', models.IntegerField()),
                ('transaction_id', models.CharField()),
                ('utr', models.CharField()),
                ('local', models.IntegerField()),
                ('hamali', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('st_charges', models.IntegerField()),
                ('other_charges', models.IntegerField()),
                ('remark', models.CharField()),
                ('sub_total', models.IntegerField()),
                ('previous_amount', models.IntegerField()),
                ('pending_amount', models.IntegerField()),
                ('total_hire_to_pay_to_vehicle', models.IntegerField(default=0)),
                ('advance_amount_to_paid_to_vehicle', models.IntegerField(default=0)),
                ('balance_amount_to_pay_to_vehicle', models.IntegerField(default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.party')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedBookVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(blank=True)),
                ('to_city', models.CharField(blank=True)),
                ('total_hire', models.IntegerField(default=0)),
                ('advance_amount', models.IntegerField(default=0)),
                ('balance_amount', models.IntegerField(default=0)),
                ('to_pay_amount', models.IntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedPaymentRecived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField()),
                ('cash', models.IntegerField(default=0)),
                ('online', models.IntegerField(default=0)),
                ('transaction_id', models.CharField()),
                ('utr', models.CharField()),
                ('total', models.IntegerField()),
                ('previous_amount', models.IntegerField()),
                ('pending_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.party')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedPaymentSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField()),
                ('cash', models.IntegerField(default=0)),
                ('online', models.IntegerField(default=0)),
                ('transaction_id', models.CharField()),
                ('utr', models.CharField()),
                ('total', models.IntegerField()),
                ('previous_amount', models.IntegerField()),
                ('balance_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vehicle')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField()),
                ('balance_amount', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.owner')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vehicletype')),
            ],
        ),
    ]
