# Generated by Django 5.2.4 on 2025-08-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_deletedowner_deletedparty_deletedvehicletype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='to_pay_amount',
        ),
        migrations.RemoveField(
            model_name='deletedbooking',
            name='to_pay_amount',
        ),
    ]
