# Generated by Django 5.2.4 on 2025-08-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_booking_to_pay_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='website.vehicletype'),
            preserve_default=False,
        ),
    ]
