# Generated by Django 5.2.4 on 2025-08-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_booking_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_number',
        ),
    ]
