# Generated by Django 5.2.4 on 2025-08-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_booking_booking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedbooking',
            name='booking_number',
        ),
        migrations.RemoveField(
            model_name='deletedpaymentrecived',
            name='booking_number',
        ),
        migrations.RemoveField(
            model_name='paymentrecived',
            name='booking_number',
        ),
    ]
