# Generated by Django 5.2.4 on 2025-08-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_remove_deletedbooking_booking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='B0001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedbooking',
            name='booking_number',
            field=models.CharField(default='B0001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedpaymentrecived',
            name='booking_number',
            field=models.CharField(default='B0001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrecived',
            name='booking_number',
            field=models.CharField(default='B0001'),
            preserve_default=False,
        ),
    ]
